routes/web.php
<?php

use App\Http\Controllers\LinkController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
require __DIR__ . '/auth.php';




Route::middleware(['auth','web'])->prefix('dashboard')->group(function(){
    Route::get('/', function () {
        return redirect()->route('link.index');
    })->name('dashboard');

    Route::get('/logs', [\App\Http\Controllers\LogController::class, 'index'])
        ->name('log.index')
        ->middleware(['auth']);
    Route::resource('link', \App\Http\Controllers\LinkController::class)->middleware(['auth']);
});

Route::group(['middleware' => ['web']],function (){

    Route::get('/', function () {

        return view('welcome');
    });

    Route::get('/{encodedId}', [LinkController::class, 'accessEncodedLink'])
        ->name('link.access')
        ->middleware(['accessLog:encodedId']);

    Route::post('/lang/set',static function (\Illuminate\Http\Request $request){
        $lang = $request->input('lang');
        $request->session()->put('lang',$lang);
        return redirect()->back();
    })->name('lang.set');

});



Auth::routes();

app/Models/Link.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;

/**
 * @property string url
 */
class Link extends Model
{
    use HasFactory;


    public function scopeAuthUser(Builder $query)
    {
        $query->where('user_id', '=', Auth::id());
    }

    public function scopeExpired(Builder $query)
    {
        $query->where('created_at', '<', Carbon::now()->addHours(-24)->toDateTimeString());
    }


    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function generateShortUrl()
    {
        return route('link.access', [
            'encodedId' => base64_encode($this->id)
        ]);
    }
}

app/Models/Log.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * @property string ip
 * @property string access_date
 * @property string country
 * @property string user_agent
 * @property integer|null user_id
 */
class Log extends Model
{
    use HasFactory;
    public $timestamps = false;

    public static function traceRequest(Link $link)
    {
        $request = request();
        $log = new Log();
        $ip = $request->ip();
        $isPublicIp = filter_var($ip, FILTER_VALIDATE_IP,FILTER_FLAG_NO_RES_RANGE);

        $log->ip = $ip;
        $log->access_date = Carbon::createFromTimestamp($request->server->get('REQUEST_TIME'))->toDateTimeString();
        $log->country =  $isPublicIp ? file_get_contents("https://ipapi.co/$ip/country_name") : "(reserved)"  ;
        $log->user_agent = $request->server->get('HTTP_USER_AGENT');
        $log->user_id = Auth::id();
        $log->link_id = $link->id;
        $log->save();
    }

    public function link()
    {
        return $this->belongsTo(Link::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }


}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function links()
    {
        return $this->hasMany(Link::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/LinkController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreLinkRequest;
use App\Models\Link;
use Illuminate\Encryption\Encrypter;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Gate;

class LinkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $links = Link::query()->authUser()->orderBy('created_at','desc')->get();
        return view('link.index', compact('links'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        return view('link.create');
    }


    public function store(StoreLinkRequest $request)
    {
        $response = Gate::inspect('create', Link::class);
        if(!$response->allowed()){
            return redirect()->route('link.index')->with('errorMessage',$response->message());
        }

        $link = new Link();
        $link->url = $request->input('url');
        $link->save();
        return redirect()
            ->route('link.index')
            ->with('successMessage', 'saved');
    }


    public function accessEncodedLink($decodedId)
    {
        $link =  Link::query()->find(base64_decode($decodedId));
        return redirect()->to($link->url);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Link $link
     * @return \Illuminate\Http\Response
     */
    public function edit(Link $link)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Link $link
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Link $link)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Link $link
     * @return \Illuminate\Http\Response
     */
    public function destroy(Link $link)
    {
        $this->authorize('delete', $link);
        $link->delete();
        return redirect()
            ->route('link.index')
            ->with('successMessage', 'Deleted!');
    }
}

app/Http/Controllers/LogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Log;
use Illuminate\Http\Request;

class LogController extends Controller
{
    public function index()
    {
        $logs = Log::query()->latest('access_date')->get();
        return view('log.index',compact('logs'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
@extends('layouts.app')
@section('content')
   <div class="row">
       <div class="col-md-12">
           Dashboard
       </div>
   </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                @auth
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a
                                class="nav-link {{\Illuminate\Support\Facades\Route::is('link.index') ? 'active' :""}}"
                                href="{{ route('link.index') }}"
                            >
                                {{ __('Links') }}
                            </a>
                        </li>

                        <li class="nav-item">
                            <a
                                class="nav-link {{\Illuminate\Support\Facades\Route::is('log.index') ? 'active' :""}}"
                                href="{{ route('log.index') }}"
                            >
                                {{ __('Log') }}
                            </a>
                        </li>
                    </ul>
            @endauth

            <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        @if (Route::has('login'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                        @endif

                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                    <li class="nav-item d-flex flex-column justify-content-center">
                        @include('parts.language')
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main class="container  py-4">
        <div class="row">
            <div class="col-md-12 erors-container">
                @include('parts.alert')
            </div>
            <div class="col-md-12">
                @yield('content')
            </div>
        </div>

    </main>
</div>
</body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                    <x-nav-link :href="route('link.index')" :active="request()->routeIs('link.index')">
                        {{ __('Links') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>

resources/views/link/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-6">
            <form id="link-form" method="POST" action="{{route('link.store')}}" class="form-row">
                @csrf
                <div class="form-group col-md-12">
                    <label for="exampleInputEmail1">{{ __('Url') }}</label>
                    <input type="text" class="form-control" name="url" placeholder="{{ __('Enter Url') }}">
                </div>
                <button type="submit" class="btn btn-primary">{{ __('Create') }}</button>
            </form>
        </div>
    </div>
@endsection

resources/views/link/index.blade.php
<?php
/** @var \App\Models\Link[] $links */
?>

@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-12">

            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div class="card-title text-uppercase">
                        {{__('My Links')}}
                    </div>
                    <a class="btn btn-success" href="{{route('link.create')}}">
                        {{__('Add new link')}}
                    </a>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th>{{__('Url')}}</th>
                            <th>{{__('Short Url')}}</th>
                            <th>{{__('Creation date')}}</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($links as $index=>$link)
                            <tr>
                                <th scope="row">{{$index+1}}</th>
                                <th>{{$link->url}}</th>
                                <th>{{$link->generateShortUrl()}}</th>
                                <th>{{$link->created_at}}</th>
                                <th class="actions">
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <button form="{{$formId=uniqid('', false)}}" type="submit"  class="btn btn-danger" data-toggle="tooltip"
                                                data-placement="top" title="{{__('Delete')}}">
                                            <i class="far fa-minus-square"></i>
                                        </button>
                                        <form id="{{$formId}}" method="POST"  action="{{route('link.destroy',['link'=>$link->id])}}">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                    </div>
                                </th>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>


        </div>
    </div>
@endsection

resources/views/log/index.blade.php
<?php
/** @var  $logs Log[] */

use App\Models\Log;

?>

@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-12">

            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div class="card-title text-uppercase">User Access Logs</div>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Url</th>
                            <th>
                                {{ __('Short Url') }}
                            </th>
                            <th>
                                {{ __('Access date') }}
                            </th>
                            <th>
                                {{ __('Ip Address') }}
                            </th>
                            <th>
                                {{ __('Country') }}
                            </th>
                            <th>
                                {{ __('User Agent') }}
                            </th>
                            <th>
                                {{ __('User') }}
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($logs as $index=>$log)
                            <tr>
                                <th>{{$log->link->url}}</th>
                                <th>{{$log->link->generateShortUrl()}}</th>
                                <th>{{$log->access_date}}</th>
                                <th>{{$log->ip}}</th>
                                <th>{{$log->country}}</th>
                                <th>{{$log->user_agent}}</th>
                                <th>{{$log->user->name?? '(Guest)'}}</th>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>


        </div>
    </div>
@endsection

resources/views/parts/alert.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if ($message = session()->get('successMessage'))
    <div class="alert alert-success">

            {{ $message }}

    </div>
@endif

@if ($message = session()->get('errorMessage'))
    <div class="alert alert-danger">

            {{ $message }}

    </div>
@endif

resources/views/parts/language.blade.php
<?php
$selected = \Illuminate\Support\Facades\App::getLocale();
?>
<select name="lang" form="lang-form"   onchange="document.getElementById('lang-form').submit()">
    <option {{$selected ==="fr" ? "selected" : ""}} value="fr">fr</option>
    <option {{$selected ==="en" ? "selected" : ""}} value="en">en</option>
</select>
<form method="POST" action="{{route('lang.set')}}" id="lang-form">
@csrf
</form>